namePrefix: development-
commonLabels:
  variant: development
commonAnnotations:
  note: Hello, I am running in development environment!
namespace: development
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
resources:
- namespace.yaml
images:
- name: dennydgl1/java-hello-world
  newName: dennydgl1/java-hello-world
  newTag: "3.0"
configMapGenerator:
 - behavior: merge
   name: java-hello-world-cm
   envs: 
    - env.properties
   files:
    - application.yaml 
